config/routes.rb
Rails.application.routes.draw do
  root 'accounts#new'

  resources :accounts

end

app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :type_name

  has_attached_file :file
  validates_attachment :file,
                       presence: true,
                       content_type: { content_type: 'text/plain' },
                       size: { in: 0..10.kilobytes }
  validates :file_file_name, :format => { :with => /(^.+_(Account)_\d+\.txt$)|(^.+_Activity_\d+\.txt$)|(^.+_Position_\d+\.txt$)|(^.+_Security_\d+\.txt$)/, message: 'wrong file' }

  after_create :parse_file_name

  def parse_file_name
    f_name = File.basename self.file_file_name, '.*'
    f_name = f_name.split '_'

    self.acc_id = f_name[0]
    self.type_name = TypeName.find_or_create_by(name: f_name[1])
    self.date = Date.parse f_name[2]
    self.save
  end
end

app/models/type_name.rb
class TypeName < ActiveRecord::Base
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    ap = account_params
    count = 0
    ap[:file].each do |f|
      account = Account.new(file: f)
      count +=1  if account.save
    end

    redirect_to accounts_path, notice: "Uploaded #{count} file(s)"
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(file: [])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/_form.html.haml
= form_for @account, html: { multipart: true } do |f|
  .field
    = f.file_field :file, multiple: true
  .actions
    = submit_tag 'Upload'

app/views/accounts/edit.html.haml
%h1 Editing account

= render 'form'

= link_to 'Show', @account
\|
= link_to 'Back', accounts_path

app/views/accounts/index.html.haml
%h1 Listing accounts
%p#notice= notice

- @accounts.joins(:type_name).group_by(&:acc_id).each do |acc_name, values|
  .acc_id
    = acc_name
    - values.group_by(&:date).each do |acc_date, values_by_date|
      .date
        = acc_date.strftime('%Y-%m-%d')
        - values_by_date.each do |acc|
          .acc_type
            = acc.type_name.name


= link_to 'Upload files', new_account_path

app/views/accounts/new.html.haml
%h1 Upload files

= render 'form'

= link_to 'Account List', accounts_path

app/views/accounts/show.html.haml
%p#notice= notice

%p
  %b Acc:
  = @account.acc_id
%p
  %b Date:
  = @account.date
%p
  %b Type name:
  = @account.type_name

= link_to 'Edit', edit_account_path(@account)
\|
= link_to 'Back', accounts_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fundseeder</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>